name: 'Setup Environment (Node + pnpm + Cache + Install)'
description: 'Sets up Node.js, pnpm via Corepack, restores cache via setup-node v5, and installs dependencies'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '22'
  pnpm-version:
    description: 'pnpm version to use'
    required: false
    default: '10.15.1'
  install-command:
    description: 'Install command to run'
    required: false
    default: 'ci:install:frozen'
  working-directory:
    description: 'Working directory for the job'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Verify Playwright container environment
      shell: bash
      run: |
        if [[ "${PLAYWRIGHT_BROWSERS_PATH:-}" == "/ms-playwright" ]]; then
          echo "✅ Using Playwright container with prebaked browsers"
        else
          echo "⚠️  Not in Playwright container - browsers may need to be installed"
        fi

    - name: Enable Corepack & pin pnpm
      shell: bash
      run: |
        corepack enable
        corepack prepare pnpm@${{ inputs.pnpm-version }} --activate

    - name: Verify pnpm
      shell: bash
      run: pnpm --version

    - name: Setup Node.js (built-in pnpm cache)
      uses: actions/setup-node@v5
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        cache-dependency-path: '**/pnpm-lock.yaml'

    - name: Install dependencies (no scripts, no PW downloads)
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'
        PNPM_SKIP_LIFECYCLE_SCRIPTS: '1'
      run: pnpm install --frozen-lockfile --ignore-scripts
