name: 'Setup Environment (Node + pnpm + Cache + Install)'
description: 'Sets up Node.js, pnpm via Corepack, restores cache via setup-node v5, and installs dependencies'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '22'
  pnpm-version:
    description: 'pnpm version to use'
    required: false
    default: '10.15.1'
  install-command:
    description: 'Install command to run'
    required: false
    default: 'ci:install:frozen'
  working-directory:
    description: 'Working directory for the job'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Set Playwright env
      shell: bash
      run: |
        echo "PLAYWRIGHT_BROWSERS_PATH=$HOME/.cache/ms-playwright" >> "$GITHUB_ENV"
        echo "PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1" >> "$GITHUB_ENV"   # prevent postinstall downloads
        mkdir -p "$HOME/.cache/ms-playwright"
        chmod -R 777 "$HOME/.cache" || true

    - name: Enable Corepack & pin pnpm
      shell: bash
      run: |
        corepack enable
        corepack prepare pnpm@${{ inputs.pnpm-version }} --activate

    - name: Verify pnpm
      shell: bash
      run: pnpm --version

    - name: Setup Node.js (built-in pnpm cache)
      uses: actions/setup-node@v5
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        cache-dependency-path: '**/pnpm-lock.yaml'

    - name: Install dependencies (no browser downloads)
      shell: bash
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'
      working-directory: ${{ inputs.working-directory }}
      run: pnpm run ${{ inputs.install-command }}
