/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type NavigationItem = {
  _type: 'navigationItem';
  label?: string;
  href?: string;
};

export type HeaderEnquiry = {
  _type: 'headerEnquiry';
  label?: string;
  href?: string;
  linkText?: string;
};

export type Header = {
  _id: string;
  _type: 'header';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  navigation?: Array<
    {
      _key: string;
    } & NavigationItem
  >;
  about?: HeaderAbout;
  social?: HeaderSocial;
  contact?: HeaderContact;
};

export type HeaderContact = {
  _type: 'headerContact';
  title?: string;
  projectEnquiry?: HeaderEnquiry;
  generalEnquiry?: HeaderEnquiry;
};

export type HeaderSocial = {
  _type: 'headerSocial';
  title?: string;
  links?: Array<
    {
      _key: string;
    } & SocialLink
  >;
};

export type HeaderAbout = {
  _type: 'headerAbout';
  title?: string;
  description?: string;
};

export type Configuration = {
  _id: string;
  _type: 'configuration';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  seo?: Seo;
  accessibility?: Accessibility;
  interface?: UiInterface;
  blog?: Blog;
  forms?: Forms;
};

export type SocialLink = {
  _type: 'socialLink';
  platform?: 'linkedin' | 'instagram' | 'facebook' | 'twitter';
  url?: string;
};

export type Footer = {
  _id: string;
  _type: 'footer';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  copyright?: string;
  contact?: FooterContact;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
};

export type FooterContact = {
  _type: 'footerContact';
  email?: string;
  phone?: string;
};

export type SocialImage = {
  _type: 'socialImage';
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  alt?: string;
  caption?: string;
  platform?: 'facebook' | 'twitter' | 'linkedin' | 'instagram' | 'opengraph';
};

export type ColorVariant =
  | 'blue'
  | 'purple'
  | 'green'
  | 'pink'
  | 'yellow'
  | 'teal';

export type Forms = {
  _type: 'forms';
  messages?: FormMessages;
};

export type FormMessages = {
  _type: 'formMessages';
  required?: string;
  invalid?: string;
  success?: string;
  error?: string;
};

export type Blog = {
  _type: 'blog';
  labels?: BlogLabels;
  paths?: BlogPaths;
};

export type BlogPaths = {
  _type: 'blogPaths';
  blog?: string;
};

export type BlogLabels = {
  _type: 'blogLabels';
  featured?: string;
  readArticle?: string;
};

export type UiInterface = {
  _type: 'uiInterface';
  mobileMenu?: MobileMenu;
  themeToggle?: ThemeToggle;
  buttons?: ButtonLabels;
};

export type ButtonLabels = {
  _type: 'buttonLabels';
  loadMore?: string;
  readMore?: string;
  submit?: string;
  close?: string;
};

export type ThemeToggle = {
  _type: 'themeToggle';
  label?: string;
};

export type MobileMenu = {
  _type: 'mobileMenu';
  toggleButton?: string;
  menuLabel?: string;
  closeButton?: string;
};

export type Accessibility = {
  _type: 'accessibility';
  closeButtons?: CloseButtons;
  calendar?: CalendarNavigation;
};

export type CalendarNavigation = {
  _type: 'calendarNavigation';
  previousMonth?: string;
  nextMonth?: string;
};

export type CloseButtons = {
  _type: 'closeButtons';
  toast?: string;
  modal?: string;
};

export type Seo = {
  _type: 'seo';
  title?: string;
  description?: string;
  keywords?: Array<string>;
  image?: AccessibleImage;
  googleSiteVerification?: string;
  bingSiteVerification?: string;
};

export type Testimonial = {
  _type: 'testimonial';
  quote?: string;
  name?: string;
  role?: string;
  image?: AccessibleImage;
};

export type TimeSlot = {
  _type: 'timeSlot';
  startTime?: string;
  endTime?: string;
  isAvailable?: boolean;
};

export type FormFieldOption = {
  _type: 'formFieldOption';
  label?: string;
  value?: string;
};

export type FormField = {
  _type: 'formField';
  label?: string;
  type?: 'text' | 'email' | 'textarea' | 'select';
  required?: boolean;
  placeholder?: string;
  options?: Array<
    {
      _key: string;
    } & FormFieldOption
  >;
};

export type TimelineEvent = {
  _type: 'timelineEvent';
  title?: string;
  description?: string;
  date?: string;
  variant?: ColorVariant;
};

export type FaqItem = {
  _type: 'faqItem';
  question?: string;
  answer?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'normal' | 'h2' | 'h3' | 'h4';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          isExternal?: boolean;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | ({
        _key: string;
      } & AccessibleImage)
  >;
};

export type PricingCard = {
  _type: 'pricingCard';
  title?: string;
  description?: string;
  price?: string;
  features?: Array<{
    text?: string;
    _type: 'feature';
    _key: string;
  }>;
  isPopular?: boolean;
  callToAction?: CallToAction;
  variant?: ColorVariant;
};

export type FeatureItem = {
  _type: 'featureItem';
  title?: string;
  description?: string;
  image?: AccessibleImage;
  link?: Link;
};

export type Card = {
  _type: 'card';
  title?: string;
  description?: string;
  featured?: boolean;
  date?: string;
  categories?: Array<string>;
  slug?: string;
  image?: AccessibleImage;
  variant?: ColorVariant;
  reverse?: boolean;
  border?: boolean;
};

export type Link = {
  _type: 'link';
  text?: string;
  url?: string;
};

export type RichText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h2' | 'h3' | 'h4';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        isExternal?: boolean;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | ({
      _key: string;
    } & AccessibleImage)
>;

export type SectionTestimonial = {
  _id: string;
  _type: 'sectionTestimonial';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  displayTitle?: string;
  description?: string;
  background?: ColorVariant;
  border?: boolean;
  testimonials?: Array<
    {
      _key: string;
    } & Testimonial
  >;
};

export type SectionCards = {
  _id: string;
  _type: 'sectionCards';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  displayTitle?: string;
  description?: string;
  background?: ColorVariant;
  border?: boolean;
  cards?: Array<
    {
      _key: string;
    } & Card
  >;
};

export type SectionContent = {
  _id: string;
  _type: 'sectionContent';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  displayTitle?: string;
  description?: string;
  background?: ColorVariant;
  border?: boolean;
  content?: RichText;
};

export type SectionForm = {
  _id: string;
  _type: 'sectionForm';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  displayTitle?: string;
  description?: string;
  background?: ColorVariant;
  border?: boolean;
  form?: FormConfiguration;
};

export type FormConfiguration = {
  _type: 'formConfiguration';
  emailTo?: string;
  emailSubject?: string;
  submitLabel?: string;
};

export type SectionFeatured = {
  _id: string;
  _type: 'sectionFeatured';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  displayTitle?: string;
  description?: string;
  background?: ColorVariant;
  border?: boolean;
  image?: AccessibleImage;
  cta?: CallToAction;
  reverse?: boolean;
};

export type CallToAction = {
  _type: 'callToAction';
  label?: string;
  href?: string;
  variant?:
    | 'black'
    | 'transparent'
    | 'blue'
    | 'purple'
    | 'green'
    | 'pink'
    | 'yellow'
    | 'teal';
  isExternal?: boolean;
};

export type SectionCalendar = {
  _id: string;
  _type: 'sectionCalendar';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  displayTitle?: string;
  description?: string;
  background?: ColorVariant;
  border?: boolean;
  settings?: CalendarSettings;
};

export type CalendarSettings = {
  _type: 'calendarSettings';
  initialDate?: string;
  disabledDates?: {
    daysOfWeek?: Array<number>;
    dates?: Array<string>;
    ranges?: Array<{
      start?: string;
      end?: string;
      _key: string;
    }>;
    before?: string;
    after?: string;
  };
};

export type SectionTimeline = {
  _id: string;
  _type: 'sectionTimeline';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  displayTitle?: string;
  description?: string;
  background?: ColorVariant;
  border?: boolean;
  steps?: Array<
    {
      _key: string;
    } & TimelineEvent
  >;
};

export type SectionFAQ = {
  _id: string;
  _type: 'sectionFAQ';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  displayTitle?: string;
  description?: string;
  background?: ColorVariant;
  border?: boolean;
  items?: Array<
    {
      _key: string;
    } & FaqItem
  >;
};

export type SectionPricing = {
  _id: string;
  _type: 'sectionPricing';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  displayTitle?: string;
  description?: string;
  background?: ColorVariant;
  border?: boolean;
  packages?: Array<
    {
      _key: string;
    } & PricingCard
  >;
};

export type SectionBlog = {
  _id: string;
  _type: 'sectionBlog';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  displayTitle?: string;
  description?: string;
  background?: ColorVariant;
  border?: boolean;
  showAllPosts?: boolean;
  posts?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'post';
  }>;
  postsPerPage?: number;
  showFeaturedOnly?: boolean;
  sortOrder?: 'newest' | 'oldest';
};

export type SectionHeader = {
  _id: string;
  _type: 'sectionHeader';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  displayTitle?: string;
  description?: string;
  background?: ColorVariant;
  border?: boolean;
  ctas?: Array<
    {
      _key: string;
    } & CallToAction
  >;
};

export type Category = {
  _id: string;
  _type: 'category';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  slug?: Slug;
  color?: ColorVariant;
  header?: {
    title?: string;
    displayTitle?: string;
    description?: string;
    background?: ColorVariant;
    border?: boolean;
    ctas?: Array<
      {
        _key: string;
      } & CallToAction
    >;
    _type: 'sectionHeader';
  };
  metadata?: Metadata;
};

export type Post = {
  _id: string;
  _type: 'post';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  slug?: Slug;
  publishedAt?: string;
  categories?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'category';
  }>;
  image?: AccessibleImage;
  featured?: boolean;
  variant?: ColorVariant;
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | ({
        _key: string;
      } & AccessibleImage)
  >;
  metadata?: Metadata;
};

export type AccessibleImage = {
  _type: 'accessibleImage';
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  alt?: string;
  caption?: string;
};

export type PrivacyPage = {
  _id: string;
  _type: 'privacyPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  sections?: Array<
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionHeader';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionBlog';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionPricing';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionFAQ';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionTimeline';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionCalendar';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionFeatured';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionForm';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionContent';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionCards';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionTestimonial';
      }
  >;
  metadata?: Metadata;
};

export type VoorwaardenPage = {
  _id: string;
  _type: 'voorwaardenPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  sections?: Array<
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionHeader';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionBlog';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionPricing';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionFAQ';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionTimeline';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionCalendar';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionFeatured';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionForm';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionContent';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionCards';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionTestimonial';
      }
  >;
  metadata?: Metadata;
};

export type ContactPage = {
  _id: string;
  _type: 'contactPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  sections?: Array<
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionHeader';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionBlog';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionPricing';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionFAQ';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionTimeline';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionCalendar';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionFeatured';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionForm';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionContent';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionCards';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionTestimonial';
      }
  >;
  metadata?: Metadata;
};

export type BlogPage = {
  _id: string;
  _type: 'blogPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  sections?: Array<
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionHeader';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionBlog';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionPricing';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionFAQ';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionTimeline';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionCalendar';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionFeatured';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionForm';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionContent';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionCards';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionTestimonial';
      }
  >;
  metadata?: Metadata;
};

export type ApproachPage = {
  _id: string;
  _type: 'approachPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  sections?: Array<
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionHeader';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionBlog';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionPricing';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionFAQ';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionTimeline';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionCalendar';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionFeatured';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionForm';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionContent';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionCards';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionTestimonial';
      }
  >;
  metadata?: Metadata;
};

export type CoachingPage = {
  _id: string;
  _type: 'coachingPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  sections?: Array<
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionHeader';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionBlog';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionPricing';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionFAQ';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionTimeline';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionCalendar';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionFeatured';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionForm';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionContent';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionCards';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionTestimonial';
      }
  >;
  metadata?: Metadata;
};

export type AboutPage = {
  _id: string;
  _type: 'aboutPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  sections?: Array<
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionHeader';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionBlog';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionPricing';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionFAQ';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionTimeline';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionCalendar';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionFeatured';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionForm';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionContent';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionCards';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionTestimonial';
      }
  >;
  metadata?: Metadata;
};

export type HomePage = {
  _id: string;
  _type: 'homePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  sections?: Array<
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionHeader';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionBlog';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionPricing';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionFAQ';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionTimeline';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionCalendar';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionFeatured';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionForm';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionContent';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionCards';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sectionTestimonial';
      }
  >;
  metadata?: Metadata;
};

export type Metadata = {
  _type: 'metadata';
  title?: string;
  description?: string;
  image?: AccessibleImage;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes =
  | NavigationItem
  | HeaderEnquiry
  | Header
  | HeaderContact
  | HeaderSocial
  | HeaderAbout
  | Configuration
  | SocialLink
  | Footer
  | FooterContact
  | SocialImage
  | ColorVariant
  | Forms
  | FormMessages
  | Blog
  | BlogPaths
  | BlogLabels
  | UiInterface
  | ButtonLabels
  | ThemeToggle
  | MobileMenu
  | Accessibility
  | CalendarNavigation
  | CloseButtons
  | Seo
  | Testimonial
  | TimeSlot
  | FormFieldOption
  | FormField
  | TimelineEvent
  | FaqItem
  | PricingCard
  | FeatureItem
  | Card
  | Link
  | RichText
  | SectionTestimonial
  | SectionCards
  | SectionContent
  | SectionForm
  | FormConfiguration
  | SectionFeatured
  | CallToAction
  | SectionCalendar
  | CalendarSettings
  | SectionTimeline
  | SectionFAQ
  | SectionPricing
  | SectionBlog
  | SectionHeader
  | Category
  | Post
  | AccessibleImage
  | PrivacyPage
  | VoorwaardenPage
  | ContactPage
  | BlogPage
  | ApproachPage
  | CoachingPage
  | AboutPage
  | HomePage
  | Metadata
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
