/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type NavigationItem = {
  _type: "navigationItem";
  label?: string;
  href?: string;
};

export type HeaderEnquiry = {
  _type: "headerEnquiry";
  label?: string;
  href?: string;
  linkText?: string;
};

export type Header = {
  _id: string;
  _type: "header";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  navigation?: Array<
    {
      _key: string;
    } & NavigationItem
  >;
  about?: HeaderAbout;
  social?: HeaderSocial;
  contact?: HeaderContact;
};

export type HeaderContact = {
  _type: "headerContact";
  title?: string;
  projectEnquiry?: HeaderEnquiry;
  generalEnquiry?: HeaderEnquiry;
};

export type HeaderSocial = {
  _type: "headerSocial";
  title?: string;
};

export type HeaderAbout = {
  _type: "headerAbout";
  title?: string;
  description?: string;
};

export type Configuration = {
  _id: string;
  _type: "configuration";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  seo?: Seo;
  accessibility?: Accessibility;
  interface?: UiInterface;
  blog?: Blog;
  forms?: Forms;
};

export type SocialLink = {
  _type: "socialLink";
  platform?: "instagram" | "linkedin";
  url?: string;
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  copyright?: string;
  contact?: FooterContact;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
};

export type FooterContact = {
  _type: "footerContact";
  email?: string;
  phone?: string;
};

export type Forms = {
  _type: "forms";
  messages?: FormMessages;
};

export type FormMessages = {
  _type: "formMessages";
  required?: string;
  invalid?: string;
  success?: string;
  error?: string;
};

export type Blog = {
  _type: "blog";
  labels?: BlogLabels;
  paths?: BlogPaths;
};

export type BlogPaths = {
  _type: "blogPaths";
  blog?: string;
};

export type BlogLabels = {
  _type: "blogLabels";
  featured?: string;
  readArticle?: string;
};

export type UiInterface = {
  _type: "uiInterface";
  mobileMenu?: MobileMenu;
  themeToggle?: ThemeToggle;
  buttons?: ButtonLabels;
};

export type ButtonLabels = {
  _type: "buttonLabels";
  loadMore?: string;
  readMore?: string;
  submit?: string;
  close?: string;
};

export type ThemeToggle = {
  _type: "themeToggle";
  label?: string;
};

export type MobileMenu = {
  _type: "mobileMenu";
  toggleButton?: string;
  menuLabel?: string;
  closeButton?: string;
};

export type Accessibility = {
  _type: "accessibility";
  closeButtons?: CloseButtons;
  calendar?: CalendarNavigation;
};

export type CalendarNavigation = {
  _type: "calendarNavigation";
  previousMonth?: string;
  nextMonth?: string;
};

export type CloseButtons = {
  _type: "closeButtons";
  toast?: string;
  modal?: string;
};

export type Seo = {
  _type: "seo";
  keywords?: Array<string>;
  defaultMetaImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    _type: "image";
  };
};

export type GoogleBot = {
  _type: "googleBot";
  index?: boolean;
  follow?: boolean;
};

export type TwitterImage = {
  _type: "twitterImage";
  url?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
};

export type OpenGraphImage = {
  _type: "openGraphImage";
  url?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  width?: number;
  height?: number;
  alt?: string;
};

export type Robots = {
  _type: "robots";
  index?: boolean;
  follow?: boolean;
  googleBot?: GoogleBot;
};

export type Twitter = {
  _type: "twitter";
  card?: "summary" | "summary_large_image";
  site?: string;
  creator?: string;
  image?: TwitterImage;
};

export type OpenGraph = {
  _type: "openGraph";
  title?: string;
  description?: string;
  type?: string;
  url?: string;
  siteName?: string;
  image?: OpenGraphImage;
};

export type Testimonial = {
  _type: "testimonial";
  quote?: string;
  name?: string;
  role?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type TimeSlot = {
  _type: "timeSlot";
  startTime?: string;
  endTime?: string;
};

export type FormFieldOption = {
  _type: "formFieldOption";
  label?: string;
  value?: string;
};

export type FormField = {
  _type: "formField";
  label?: string;
  type?: "text" | "email" | "textarea" | "select";
  required?: boolean;
  placeholder?: string;
  options?: Array<
    {
      _key: string;
    } & FormFieldOption
  >;
};

export type TimelineEvent = {
  _type: "timelineEvent";
  title?: string;
  date?: string;
  description?: string;
};

export type FaqItem = {
  _type: "faqItem";
  question?: string;
  answer?: string;
};

export type PricingCard = {
  _type: "pricingCard";
  title?: string;
  price?: string;
  description?: string;
  features?: Array<string>;
  isPopular?: boolean;
  variant?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
  cta?: CallToAction;
};

export type FeatureItem = {
  _type: "featureItem";
  title?: string;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Card = {
  _type: "card";
  title?: string;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  link?: Link;
};

export type Link = {
  _type: "link";
  text?: string;
  url?: string;
};

export type SectionTestimonial = {
  _id: string;
  _type: "sectionTestimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  displayTitle?: string;
  subtitle?: string;
  background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
  description?: string;
  testimonials?: Array<
    {
      _key: string;
    } & Testimonial
  >;
};

export type SectionCards = {
  _id: string;
  _type: "sectionCards";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  displayTitle?: string;
  subtitle?: string;
  background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
  description?: string;
  cards?: Array<
    {
      _key: string;
    } & Card
  >;
};

export type SectionContent = {
  _id: string;
  _type: "sectionContent";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  displayTitle?: string;
  subtitle?: string;
  background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "h4";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
};

export type SectionForm = {
  _id: string;
  _type: "sectionForm";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  displayTitle?: string;
  subtitle?: string;
  background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
  description?: string;
  form?: FormConfiguration;
};

export type FormConfiguration = {
  _type: "formConfiguration";
  emailTo?: string;
  emailSubject?: string;
  fields?: Array<
    {
      _key: string;
    } & FormField
  >;
};

export type SectionFeatured = {
  _id: string;
  _type: "sectionFeatured";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  displayTitle?: string;
  subtitle?: string;
  background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
  description?: string;
  items?: Array<
    {
      _key: string;
    } & FeatureItem
  >;
};

export type SectionCalendar = {
  _id: string;
  _type: "sectionCalendar";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  displayTitle?: string;
  subtitle?: string;
  background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
  description?: string;
  settings?: CalendarSettings;
};

export type CalendarSettings = {
  _type: "calendarSettings";
  availableDays?: Array<string>;
  availableTimeSlots?: Array<
    {
      _key: string;
    } & TimeSlot
  >;
  excludedDates?: Array<string>;
};

export type SectionTimeline = {
  _id: string;
  _type: "sectionTimeline";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  displayTitle?: string;
  subtitle?: string;
  background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
  description?: string;
  events?: Array<
    {
      _key: string;
    } & TimelineEvent
  >;
};

export type SectionFAQ = {
  _id: string;
  _type: "sectionFAQ";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  displayTitle?: string;
  subtitle?: string;
  background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
  description?: string;
  questions?: Array<
    {
      _key: string;
    } & FaqItem
  >;
};

export type SectionPricing = {
  _id: string;
  _type: "sectionPricing";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  displayTitle?: string;
  subtitle?: string;
  background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
  description?: string;
  pricingCards?: Array<
    {
      _key: string;
    } & PricingCard
  >;
};

export type SectionBlog = {
  _id: string;
  _type: "sectionBlog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  displayTitle?: string;
  subtitle?: string;
  background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
  description?: string;
  postsToShow?: number;
  showFeaturedOnly?: boolean;
  sortOrder?: "newest" | "oldest";
};

export type SectionHeader = {
  _id: string;
  _type: "sectionHeader";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  displayTitle?: string;
  subtitle?: string;
  background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  cta?: CallToAction;
};

export type CallToAction = {
  _type: "callToAction";
  text?: string;
  link?: string;
  variant?: "primary" | "secondary" | "text";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  slug?: Slug;
  publishedAt?: string;
  categories?: Array<string>;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  featured?: boolean;
  variant?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
  >;
  metadata?: Metadata;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  sections?: Array<
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        image?: {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        cta?: CallToAction;
        _type: "sectionHeader";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        postsToShow?: number;
        showFeaturedOnly?: boolean;
        sortOrder?: "newest" | "oldest";
        _type: "sectionBlog";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        pricingCards?: Array<
          {
            _key: string;
          } & PricingCard
        >;
        _type: "sectionPricing";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        questions?: Array<
          {
            _key: string;
          } & FaqItem
        >;
        _type: "sectionFAQ";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        events?: Array<
          {
            _key: string;
          } & TimelineEvent
        >;
        _type: "sectionTimeline";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        settings?: CalendarSettings;
        _type: "sectionCalendar";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        items?: Array<
          {
            _key: string;
          } & FeatureItem
        >;
        _type: "sectionFeatured";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        form?: FormConfiguration;
        _type: "sectionForm";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        content?: Array<
          | {
              children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: "span";
                _key: string;
              }>;
              style?: "normal" | "h2" | "h3" | "h4";
              listItem?: "bullet" | "number";
              markDefs?: Array<{
                href?: string;
                _type: "link";
                _key: string;
              }>;
              level?: number;
              _type: "block";
              _key: string;
            }
          | {
              asset?: {
                _ref: string;
                _type: "reference";
                _weak?: boolean;
                [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
              };
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              _type: "image";
              _key: string;
            }
        >;
        _type: "sectionContent";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        cards?: Array<
          {
            _key: string;
          } & Card
        >;
        _type: "sectionCards";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        testimonials?: Array<
          {
            _key: string;
          } & Testimonial
        >;
        _type: "sectionTestimonial";
        _key: string;
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionHeader";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionBlog";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionPricing";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionFAQ";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionTimeline";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionCalendar";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionFeatured";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionForm";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionContent";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionCards";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionTestimonial";
      }
  >;
  metadata?: Metadata;
};

export type BlogPage = {
  _id: string;
  _type: "blogPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  sections?: Array<
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        image?: {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        cta?: CallToAction;
        _type: "sectionHeader";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        postsToShow?: number;
        showFeaturedOnly?: boolean;
        sortOrder?: "newest" | "oldest";
        _type: "sectionBlog";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        pricingCards?: Array<
          {
            _key: string;
          } & PricingCard
        >;
        _type: "sectionPricing";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        questions?: Array<
          {
            _key: string;
          } & FaqItem
        >;
        _type: "sectionFAQ";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        events?: Array<
          {
            _key: string;
          } & TimelineEvent
        >;
        _type: "sectionTimeline";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        settings?: CalendarSettings;
        _type: "sectionCalendar";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        items?: Array<
          {
            _key: string;
          } & FeatureItem
        >;
        _type: "sectionFeatured";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        form?: FormConfiguration;
        _type: "sectionForm";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        content?: Array<
          | {
              children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: "span";
                _key: string;
              }>;
              style?: "normal" | "h2" | "h3" | "h4";
              listItem?: "bullet" | "number";
              markDefs?: Array<{
                href?: string;
                _type: "link";
                _key: string;
              }>;
              level?: number;
              _type: "block";
              _key: string;
            }
          | {
              asset?: {
                _ref: string;
                _type: "reference";
                _weak?: boolean;
                [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
              };
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              _type: "image";
              _key: string;
            }
        >;
        _type: "sectionContent";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        cards?: Array<
          {
            _key: string;
          } & Card
        >;
        _type: "sectionCards";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        testimonials?: Array<
          {
            _key: string;
          } & Testimonial
        >;
        _type: "sectionTestimonial";
        _key: string;
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionHeader";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionBlog";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionPricing";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionFAQ";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionTimeline";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionCalendar";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionFeatured";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionForm";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionContent";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionCards";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionTestimonial";
      }
  >;
  metadata?: Metadata;
};

export type ApproachPage = {
  _id: string;
  _type: "approachPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  sections?: Array<
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        image?: {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        cta?: CallToAction;
        _type: "sectionHeader";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        postsToShow?: number;
        showFeaturedOnly?: boolean;
        sortOrder?: "newest" | "oldest";
        _type: "sectionBlog";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        pricingCards?: Array<
          {
            _key: string;
          } & PricingCard
        >;
        _type: "sectionPricing";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        questions?: Array<
          {
            _key: string;
          } & FaqItem
        >;
        _type: "sectionFAQ";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        events?: Array<
          {
            _key: string;
          } & TimelineEvent
        >;
        _type: "sectionTimeline";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        settings?: CalendarSettings;
        _type: "sectionCalendar";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        items?: Array<
          {
            _key: string;
          } & FeatureItem
        >;
        _type: "sectionFeatured";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        form?: FormConfiguration;
        _type: "sectionForm";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        content?: Array<
          | {
              children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: "span";
                _key: string;
              }>;
              style?: "normal" | "h2" | "h3" | "h4";
              listItem?: "bullet" | "number";
              markDefs?: Array<{
                href?: string;
                _type: "link";
                _key: string;
              }>;
              level?: number;
              _type: "block";
              _key: string;
            }
          | {
              asset?: {
                _ref: string;
                _type: "reference";
                _weak?: boolean;
                [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
              };
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              _type: "image";
              _key: string;
            }
        >;
        _type: "sectionContent";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        cards?: Array<
          {
            _key: string;
          } & Card
        >;
        _type: "sectionCards";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        testimonials?: Array<
          {
            _key: string;
          } & Testimonial
        >;
        _type: "sectionTestimonial";
        _key: string;
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionHeader";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionBlog";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionPricing";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionFAQ";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionTimeline";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionCalendar";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionFeatured";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionForm";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionContent";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionCards";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionTestimonial";
      }
  >;
  metadata?: Metadata;
};

export type CoachingPage = {
  _id: string;
  _type: "coachingPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  sections?: Array<
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        image?: {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        cta?: CallToAction;
        _type: "sectionHeader";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        postsToShow?: number;
        showFeaturedOnly?: boolean;
        sortOrder?: "newest" | "oldest";
        _type: "sectionBlog";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        pricingCards?: Array<
          {
            _key: string;
          } & PricingCard
        >;
        _type: "sectionPricing";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        questions?: Array<
          {
            _key: string;
          } & FaqItem
        >;
        _type: "sectionFAQ";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        events?: Array<
          {
            _key: string;
          } & TimelineEvent
        >;
        _type: "sectionTimeline";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        settings?: CalendarSettings;
        _type: "sectionCalendar";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        items?: Array<
          {
            _key: string;
          } & FeatureItem
        >;
        _type: "sectionFeatured";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        form?: FormConfiguration;
        _type: "sectionForm";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        content?: Array<
          | {
              children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: "span";
                _key: string;
              }>;
              style?: "normal" | "h2" | "h3" | "h4";
              listItem?: "bullet" | "number";
              markDefs?: Array<{
                href?: string;
                _type: "link";
                _key: string;
              }>;
              level?: number;
              _type: "block";
              _key: string;
            }
          | {
              asset?: {
                _ref: string;
                _type: "reference";
                _weak?: boolean;
                [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
              };
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              _type: "image";
              _key: string;
            }
        >;
        _type: "sectionContent";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        cards?: Array<
          {
            _key: string;
          } & Card
        >;
        _type: "sectionCards";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        testimonials?: Array<
          {
            _key: string;
          } & Testimonial
        >;
        _type: "sectionTestimonial";
        _key: string;
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionHeader";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionBlog";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionPricing";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionFAQ";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionTimeline";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionCalendar";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionFeatured";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionForm";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionContent";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionCards";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionTestimonial";
      }
  >;
  metadata?: Metadata;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  sections?: Array<
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        image?: {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        cta?: CallToAction;
        _type: "sectionHeader";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        postsToShow?: number;
        showFeaturedOnly?: boolean;
        sortOrder?: "newest" | "oldest";
        _type: "sectionBlog";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        pricingCards?: Array<
          {
            _key: string;
          } & PricingCard
        >;
        _type: "sectionPricing";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        questions?: Array<
          {
            _key: string;
          } & FaqItem
        >;
        _type: "sectionFAQ";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        events?: Array<
          {
            _key: string;
          } & TimelineEvent
        >;
        _type: "sectionTimeline";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        settings?: CalendarSettings;
        _type: "sectionCalendar";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        items?: Array<
          {
            _key: string;
          } & FeatureItem
        >;
        _type: "sectionFeatured";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        form?: FormConfiguration;
        _type: "sectionForm";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        content?: Array<
          | {
              children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: "span";
                _key: string;
              }>;
              style?: "normal" | "h2" | "h3" | "h4";
              listItem?: "bullet" | "number";
              markDefs?: Array<{
                href?: string;
                _type: "link";
                _key: string;
              }>;
              level?: number;
              _type: "block";
              _key: string;
            }
          | {
              asset?: {
                _ref: string;
                _type: "reference";
                _weak?: boolean;
                [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
              };
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              _type: "image";
              _key: string;
            }
        >;
        _type: "sectionContent";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        cards?: Array<
          {
            _key: string;
          } & Card
        >;
        _type: "sectionCards";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        testimonials?: Array<
          {
            _key: string;
          } & Testimonial
        >;
        _type: "sectionTestimonial";
        _key: string;
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionHeader";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionBlog";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionPricing";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionFAQ";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionTimeline";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionCalendar";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionFeatured";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionForm";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionContent";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionCards";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionTestimonial";
      }
  >;
  metadata?: Metadata;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  sections?: Array<
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        image?: {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        cta?: CallToAction;
        _type: "sectionHeader";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        postsToShow?: number;
        showFeaturedOnly?: boolean;
        sortOrder?: "newest" | "oldest";
        _type: "sectionBlog";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        pricingCards?: Array<
          {
            _key: string;
          } & PricingCard
        >;
        _type: "sectionPricing";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        questions?: Array<
          {
            _key: string;
          } & FaqItem
        >;
        _type: "sectionFAQ";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        events?: Array<
          {
            _key: string;
          } & TimelineEvent
        >;
        _type: "sectionTimeline";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        settings?: CalendarSettings;
        _type: "sectionCalendar";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        items?: Array<
          {
            _key: string;
          } & FeatureItem
        >;
        _type: "sectionFeatured";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        form?: FormConfiguration;
        _type: "sectionForm";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        content?: Array<
          | {
              children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: "span";
                _key: string;
              }>;
              style?: "normal" | "h2" | "h3" | "h4";
              listItem?: "bullet" | "number";
              markDefs?: Array<{
                href?: string;
                _type: "link";
                _key: string;
              }>;
              level?: number;
              _type: "block";
              _key: string;
            }
          | {
              asset?: {
                _ref: string;
                _type: "reference";
                _weak?: boolean;
                [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
              };
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              _type: "image";
              _key: string;
            }
        >;
        _type: "sectionContent";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        cards?: Array<
          {
            _key: string;
          } & Card
        >;
        _type: "sectionCards";
        _key: string;
      }
    | {
        title?: string;
        displayTitle?: string;
        subtitle?: string;
        background?: "blue" | "purple" | "green" | "pink" | "yellow" | "teal";
        description?: string;
        testimonials?: Array<
          {
            _key: string;
          } & Testimonial
        >;
        _type: "sectionTestimonial";
        _key: string;
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionHeader";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionBlog";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionPricing";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionFAQ";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionTimeline";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionCalendar";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionFeatured";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionForm";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionContent";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionCards";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sectionTestimonial";
      }
  >;
  metadata?: Metadata;
};

export type Metadata = {
  _type: "metadata";
  title?: string;
  description?: string;
  keywords?: Array<string>;
  openGraph?: OpenGraph;
  twitter?: Twitter;
  robots?: Robots;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityFileAsset
  | Geopoint
  | NavigationItem
  | HeaderEnquiry
  | Header
  | HeaderContact
  | HeaderSocial
  | HeaderAbout
  | Configuration
  | SocialLink
  | Footer
  | FooterContact
  | Forms
  | FormMessages
  | Blog
  | BlogPaths
  | BlogLabels
  | UiInterface
  | ButtonLabels
  | ThemeToggle
  | MobileMenu
  | Accessibility
  | CalendarNavigation
  | CloseButtons
  | Seo
  | GoogleBot
  | TwitterImage
  | OpenGraphImage
  | Robots
  | Twitter
  | OpenGraph
  | Testimonial
  | TimeSlot
  | FormFieldOption
  | FormField
  | TimelineEvent
  | FaqItem
  | PricingCard
  | FeatureItem
  | Card
  | Link
  | SectionTestimonial
  | SectionCards
  | SectionContent
  | SectionForm
  | FormConfiguration
  | SectionFeatured
  | SectionCalendar
  | CalendarSettings
  | SectionTimeline
  | SectionFAQ
  | SectionPricing
  | SectionBlog
  | SectionHeader
  | CallToAction
  | Post
  | ContactPage
  | BlogPage
  | ApproachPage
  | CoachingPage
  | AboutPage
  | HomePage
  | Metadata
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImageAsset
  | SanityAssetSourceData
  | SanityImageMetadata
  | Slug;
export declare const internalGroqTypeReferenceTo: unique symbol;
