import type { ComponentPropsWithoutRef, Ref } from 'react';
import { forwardRef, useId } from 'react';

import { Text } from '@/components/ui/Text';
import { Box } from '@/components/ui/Box';
import { Stack } from '@/components/ui/Stack';
import { cn } from '@/utilities/cn';

type SharedProps = {
  label?: string;
  error?: string;
  className?: string;
  variant?: 'default' | 'bordered';
  disabled?: boolean;
};

type InputKind =
  | ({ as?: 'input' } & ComponentPropsWithoutRef<'input'>)
  | ({ as: 'textarea' } & ComponentPropsWithoutRef<'textarea'>);

export type InputProps = SharedProps & InputKind;

/**
 * A minimal input component with sharp, modern styling
 */
export const Input = forwardRef<
  HTMLInputElement | HTMLTextAreaElement,
  InputProps
>(
  (
    { label, error, className, as, variant = 'default', disabled, ...props },
    ref
  ) => {
    const autogeneratedId = useId();
    const controlId = 'id' in props ? props.id : autogeneratedId;
    const errorId = `${controlId}-error`;
    const hasError = Boolean(error);
    const baseInputStyles = cn(
      'w-full px-4 py-2 transition-all duration-200 focus:outline-none placeholder:text-muted-foreground dark:placeholder:text-muted-foreground/60 text-foreground dark:text-foreground',
      /* Variant styles */
      variant === 'default' &&
        'bg-background border-b-2 border-foreground/20 focus:border-foreground dark:focus:border-foreground hover:border-foreground/40 dark:hover:border-foreground/40 disabled:bg-muted disabled:border-muted-foreground/40 disabled:text-muted-foreground disabled:cursor-not-allowed',
      variant === 'bordered' &&
        'bg-background border border-foreground/20 focus:border-foreground dark:focus:border-foreground hover:border-foreground/40 dark:hover:border-foreground/40 disabled:bg-muted disabled:border-muted-foreground/40 disabled:text-muted-foreground disabled:cursor-not-allowed',
      /* Error state */
      hasError && '!border-destructive dark:!border-destructive',
      className
    );

    return (
      <Stack space={3}>
        <Box className="group">
          {label && (
            <Box className="relative inline-block">
              <label
                htmlFor={controlId}
                className={cn(
                  'block text-sm font-medium mb-1',
                  disabled && 'opacity-60'
                )}
              >
                {label}
              </label>
              <Box
                className={cn(
                  'absolute -bottom-[2px] left-0 h-[2px] w-0 bg-primary/60 dark:bg-primary/40 transition-all duration-300 ease-out group-focus-within:w-12',
                  disabled && 'hidden'
                )}
              />
            </Box>
          )}
          <Box className="mt-3">
            {as === 'textarea' ? (
              <textarea
                id={controlId}
                ref={ref as Ref<HTMLTextAreaElement>}
                disabled={disabled}
                aria-invalid={hasError || undefined}
                aria-describedby={hasError ? errorId : undefined}
                className={cn(
                  baseInputStyles,
                  'min-h-[120px] resize-y',
                  variant === 'default' && 'border-x-0 border-t-0'
                )}
                {...(props as ComponentPropsWithoutRef<'textarea'>)}
              />
            ) : (
              <input
                id={controlId}
                ref={ref as Ref<HTMLInputElement>}
                disabled={disabled}
                aria-invalid={hasError || undefined}
                aria-describedby={hasError ? errorId : undefined}
                className={baseInputStyles}
                {...(props as ComponentPropsWithoutRef<'input'>)}
              />
            )}
          </Box>
        </Box>
        {hasError && (
          <Text
            id={errorId}
            variant="error"
            className={disabled ? 'opacity-60' : undefined}
          >
            {error}
          </Text>
        )}
      </Stack>
    );
  }
);

Input.displayName = 'Input';
